Add botamusique
flipdot/mumble-docker pull request #6
Opened 2020-03-17 23:36 UTC by 0boro

2020-03-18 07:51 UTC, cfstras requested changes
I have some feedback

2020-03-18 07:51 UTC, cfstras commented on docker-compose.yaml
> +      - 8181:8181
what's this port doing?

2020-03-18 07:51 UTC, cfstras commented on plugins/botamusique/Dockerfile
> +FROM python:alpine
pin base image to a version

2020-03-18 07:51 UTC, cfstras commented on plugins/botamusique/Dockerfile
> +RUN apk add opus opus-dev libmagic ffmpeg
merge all `apk add` into one RUN command
you can split the line:
```docker
RUN apk add this that \
    other things
```

2020-03-18 07:51 UTC, cfstras commented on plugins/botamusique/configuration.ini
> +database_path = database.db
add a volume (to dockerfile _and_ docker-compose file) to persist the database?

2020-03-18 07:51 UTC, cfstras commented on plugins/botamusique/Dockerfile
> +RUN git clone --branch ${VERSION} --recurse-submodules https://github.com/azlux/botamusique.git
why not a submodule? lets us pin the exact revision

2020-03-20 22:32 UTC, 0boro commented
sry for my `git commit --amend` behaviour, someone needs to exorcise Gerrit of me.

2020-03-21 01:32 UTC, LennyPenny approved these changes

2020-03-21 01:40 UTC, merged